#!/bin/bash

nc='\033[0m'
fg='\033[38;2'
bg='48;2'
i='\033[3'
m='m'
n='1'

# 🇬🇧 Derived of League of Legends site pages
# 🇵🇹 Derivado da página de Universo do site League of Legends
# 1: https://universe.leagueoflegends.com/pt_BR/
# 2: https://universe.leagueoflegends.com/pt_BR/region/piltover/
# 3: https://na.leagueoflegends.com/en/featured/piltover

cor01='250;247;241' # @ #faf7f1
cor02='211;199;170' # @ #d3c7aa
cor03='133;133;105' # @ #858569
cor04='124;108;72'  # @ #7c6c48
cor05='100;83;57'   # @ #645339
cor06='67;52;31'    # @ #43341f
cor07='52;43;32'    # @ #342b20
cor08='17;17;20'    # @ #111114
cor09='11;11;11'    # @ #0b0b0b
cor10='16;18;23'    # @ #101217
cor11='20;24;29'    # @ #14181d
cor12='205;190;145' # @ #cdbe91
cor13='156;126;68'  # @ #9c7e44
cor14='147;115;65'  # @ #937341
cor15='114;82;38'   # @ #725226
cor16='15;161;166'  # @ #0fa1a6
cor17='7;120;142'   # @ #07788e

italico()
{
  printf "${i}${m}$@${nc}\n";
}

piltover_1()
{
  printf "${fg};${cor01};${m}$@${nc}\n";
}

piltover_2()
{
  printf "${fg};${cor02};${n}${m}$@${nc}\n";
}

piltover_3()
{
  printf "${fg};${cor13};${n}${m}$@${nc}\n";
}

shurima_1()
{
  printf "${fg};${cor03}${m}$@${nc}\n";
}

shurima_2()
{
  printf "${fg};${cor03};${n}${m}$@${nc}\n";
}

shurima_3()
{
  printf "${fg};${cor12};${bg};${cor15};${n}${m}$@${nc}\n";
}

zaun_1()
{
  printf "${fg};${cor17}${m}$@${nc}\n";
}

zaun_2()
{
  printf "${fg};${cor16};${n}${m}$@${nc}\n";
}

zaun_3()
{
  printf "${fg};${cor16};${bg};${cor11};${n}${m}$@${nc}\n";
}

echo -en "$(piltover_1 'Escolhe um número para seleccionar distribuição'): \n"

echo -en "$(piltover_3 a): arch \n"
echo -en "$(piltover_3 r): redhat \n"
echo -en "$(piltover_3 u): ubuntu \n"
read distro

case $distro in
  a) 
    distroname=arch
    ;;
  r) 
    distroname=redhat
    ;;
  u) 
    distroname=ubuntu
    ;;
  *) 
    echo -en "Número inválido.\n"
    ;;
esac

echo -en "$(piltover_1 'Escolhe um número para seleccionar a') $(italico tag): \n"

echo -en "$(shurima_3 'WSL 1')\n"
echo -en "$(piltover_3 1): minimal-wsl-1 \n"
echo -en "$(piltover_3 2): mid-wsl-1 \n"
echo -en "$(piltover_3 3): full-wsl-1 \n"
echo -en "$(piltover_3 4): full-miktex-wsl-1 \n"

echo -en "\n"

echo -en "$(shurima_3 'WSL 2')\n"
echo -en "$(piltover_3 5): minimal \n"
echo -en "$(piltover_3 6): latest \n"
echo -en "$(piltover_3 7): latest-miktex \n"

read tag

case $tag in
  1) 
    tagname=minimal-wsl-1
    ;;
  2) 
    tagname=mid-wsl-1
    ;;
  3) 
    tagname=full-wsl-1
    ;;
  4) 
    tagname=full-miktex-wsl-1
    ;;
  5) 
    tagname=minimal
    ;;
  6) 
    tagname=latest
    ;;
  7) 
    tagname=latest-miktex
    ;;
  *) 
    echo -en "Número inválido.\n"
    ;;
esac

echo -en "$(piltover_1 'Escolhe um número para construir ou publicar a imagem do Docker'): \n"
echo -en "$(piltover_3 1): build \n"
echo -en "$(piltover_3 2): push \n"

read dev

capitalise=$(sed 's/^./\u&/; s/-\(.\)/ \u\1/g' <<< $distroname)

case $dev in
  1) 
    echo -en "$(piltover_2 Construição) da imagem da distirbuição $(piltover_2 $capitalise) na $(italico tag) $(piltover_2 $tagname).\n";
    # echo -en "docker build -f complete-$distroname/$tagname.dockerfile -t gusbemacbe/complete-$distroname:$tagname . | sed '/^Step/d; /^Running/d";
    docker build -f complete-$distroname/$tagname.dockerfile -t gusbemacbe/complete-$distroname:$tagname . | sed '/^Step/d; /^Running/d';
    echo -en "\n";
    ;;
  2) 
    echo -en "$(piltover_2 Publicação) da imagem da distirbuição $(piltover_2 $capitalise) na $(italico tag) $(piltover_2 $tagname).\n";
    # echo -en "docker push gusbemacbe/complete-$distroname:$tagname";
    docker push gusbemacbe/complete-$distroname:$tagname
    echo -en "\n";
    ;;
  *)
    echo -en "Número inválido.\n";
    ;;
esac